version: '3.7'

services:
  postgres:
    image: postgres:10
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    ports:
      - 5432:5432

  odoo:
    image: odoo:12
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf
    ports:
      - 8069:8069

volumes:
  postgres:
    name: odoo_postgres
